#!/usr/bin/env zsh

###
# Print usage information
###
function _zulu_usage() {
  echo $(color yellow "Usage:")
  echo "  zulu [options] <command>"
  echo
  echo $(color yellow "Options:")
  echo "  -h, --help          Output this help text and exit"
  echo "  -v, --version       Output version information and exit"
  echo
  echo $(color yellow "Commands:")
  echo "  install <package>     Install a package"
  echo "  uninstall <package>   Uninstall a package"
  echo "  upgrade <package>     Upgrade a package"
  echo "  link <package>        Create symlinks for a package"
  echo "  unlink <package>      Remove symlinks for a package"
  echo "  list                  List packages"
  echo "  info                  Show information for a package"
  echo "  search                Search the package index"
  echo "  alias <args>          Functions for adding/removing aliases"
  echo "  path <args>           Functions for adding/removing dirs from \$PATH"
  echo "  fpath <args>          Functions for adding/removing dirs from \$fpath"
  echo "  cdpath <args>         Functions for adding/removing dirs from \$cdpath"
  echo "  update                Update the package index"
  echo "  self-update           Update zulu"
}

function _zulu_version() {
  cat "$base/core/.version"
}

###
# The main zulu command. Loads and executes all other commands
###
(( $+functions[zulu] )) || function zulu() {
  local cmd base help version

  # Set up some source paths
  base=${ZULU_DIR:-"${ZDOTDIR:-$HOME}/.zulu"}
  config=${ZULU_CONFIG_DIR:-"${ZDOTDIR:-$HOME}/.config/zulu"}

  # Parse CLI options
  zparseopts -D h=help -help=help v=version -version=version

  # Print help
  if [[ -n $help ]]; then
    _zulu_usage
    return
  fi

  if [[ -n $version ]]; then
    _zulu_version
    return
  fi

  cmd="$1"

  # The init command needs to be loaded itself
  if [[ $cmd = 'init' ]]; then
    if (( ! $+functions[_zulu_init] )); then
      source "$base/core/commands/init"
    fi
  fi

  if [[ -z $cmd ]]; then
    echo " _____         ___"
    echo "/__  /  __  __/  /_  __"
    echo "  / /  / / / /  / / / /"
    echo " / /__/ /_/ /  / /_/ /"
    echo "/____/\\____/__/\\____/"
    echo
    echo "Version $(zulu --version)"
    echo
    _zulu_usage
    return
  fi

  # Check if the requested command exists
  if (( ! $+functions[_zulu_${cmd}] )); then
    # If it doesn't, print usage information and exit
    echo $(color red "Command '$cmd' can not be found.")
    echo
    _zulu_usage
    return 1
  fi

  # Execute the requested command
  _zulu_${cmd} "${(@)@:2}"
}
