#!/usr/bin/env zsh

###
# Output usage information
###
function _zulu_theme_usage() {
  echo $(color yellow "Usage:")
  echo "  zulu theme <theme_name>"
}

_zulu_theme() {
  local base theme config config_dir

  theme="$1"

  # Parse options
  zparseopts -D h=help -help=help

  # Output help and return if requested
  if [[ $help ]]; then
    _zulu_theme_usage
    return
  fi

  # Set up some variables
  base=${ZULU_DIR:-"${ZDOTDIR:-$HOME}/.zulu"}
  config_dir=${ZULU_CONFIG_DIR:-"${ZDOTDIR:-$HOME}/.config/zulu"}
  config="${config_dir}/theme"

  echo "$theme" >! $config

  # Ensure promptinit is loaded
  autoload -U promptinit && promptinit

  prompt $theme
}
